#!/bin/bash
#
# Run one-by-one for each sub-project
#
set -e # exit immediately if a command exits with a nonzero exit value
CMD=$@

projects=(@grammarly/focal focal-manual-tests focal-todomvc focal-examples)
for project in "${projects[@]}"
do
  echo "Running: yarn workspace $project $CMD"
  yarn workspace $project $CMD
done
