name: Debug

on: [pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/debug-action@v2
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn test
      - run: yarn package
