name: Debug

on: [pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TEST: '[{"name": "@grammarly/focal", "version": "1.2.0"}, {"name": "@grammarly/focal-atom", "version": "0.8.9"}]'
    steps:
      # - uses: hmarr/debug-action@v2
      - run: 'echo "json: $TEST"'
      # - run: echo ${{ fromJson(env.TEST) }}
      - uses: edwardgeorge/jq-action@v1
        id: jq
        with:
          input: ${{ env.TEST }}
          script: 'map({ key: .name, value: .version }) | from_entries | { focal: .["@grammarly/focal"], focalAtom: .["@grammarly/focal-atom"] }'
      - run: 'echo "${{ steps.jq.outputs.output }}"'
      - if: ${{ fromJson(steps.jq.outputs.output).focal }}
        run: echo "Found @grammarly/focal ${{ fromJson(steps.jq.outputs.output).focal }}"
      - if: ${{ fromJson(steps.jq.outputs.output)['focalAtom'] }}
        run: echo "Found @grammarly/focal ${{ fromJson(steps.jq.outputs.output)['focalAtom'] }}"
